### ISSUE TITLE
What's the process for merging pull requests?

### ISSUE THREAD

**Issue by morewry** [opentable/design-tokens#62] opened 2017-10-27 01:47 UTC
What is the process for merging pull requests to this repo? Especially if we begin to add restaurant-only tokens, who is empowered to merge and to publish? Does it depend on who owns that set of tokens?

**Comment by matteofigus** [comment] 2017-10-27 10:41
There is not a "formal" process yet. 
My **personal** take/wish would be:
* All PRs (coming from Design or Engineers) merged by Design
* When in need of engineers, Design can ask for co-reviewers

But I admit this may be not the current flow and we are working on it. What would be your take on it @morewry @mannionaco @francesyun @nickbalestra ?

**Comment by morewry** [comment] 2017-10-27 16:23
Oh, interesting! I didn't realize the idea might be that design would be the primary owners of this repo, but that makes a lot of sense, should it work out.

However, if that's the case, I want engineers to have some better options (or shortcut for setting up) to be able to work with changes locally before PRs are made and while they are pending. Since this is a separate repo, we'll have to use e.g. `npm link` locally. GCUIC, having so many repos, had this issue on a much more massive scale, and so maybe with only one or two links required the result won't be the same. However, we found with GCUIC that many developers did not find that an ergonomic development experience and avoided doing it, resulting in a more frustrating experience for them while developing components and resulting in their also avoiding developing on components.

**Comment by matteofigus** [comment] 2017-10-27 16:30
@morewry out of curiosity, why would you (engineer) want to change the DT?

I think (and again, opinions my own 🤣 ) one of the ideas I have is that we should be barely consuming these values - deciding how to code this values and, in case, fix them, should belong to design. My vision is that if you are building a component that depends on a DT and you need to change something because you can't build what designers asked you to build, you should talk with them and ask them to change it. Despite this could sound time consuming and blocking, I think this would kind of facilitate design to have this kind of conversations and take ownership of their own decisions during time. Perhaps finding out that some tokens have been coded in such way conflicts emerge and so decisions need to be revisited.

I really would love some design input here like @mannionaco's :)

**Comment by morewry** [comment] 2017-10-27 17:15
Well, all the reasons come down to that we don't have any of that in place. 

My past experience at OT is that, despite design owning the definitions, it's the engineers who actually set up the variables, because they're code. The conversation in https://github.com/opentable/design-tokens/issues/52 is super relevant here. It sounds in that thread like there's a disconnect between how the majority of engineers who've participated in the discussion so far would prefer to do naming and how design intends to do the naming. But if we agreed on the alias approach, developers would be likely to be routinely adding aliases. The point of a design system is to empower us to not _have to always_ ask design what color to use before we begin working because we'll be able to follow the rules within the system or see the global name of the color in a spec and go ahead and set up appropriate aliases for the work we're about to do.

The next things motivating my concern about stem from you and I having different perspectives and situations as people who primarily develop for different divisions (diner vs restaurant).

Diner's design system is already under way. Restaurant's is not--or, if it is, the info hasn't gotten to some of the people who most need to know that, like myself. I've heard that they may be starting earlier on some of the tokens, but the last word I had was that they'd be starting in Q1. So we don't have the option of "barely consuming" what design has set. Design hasn't set anything. And, at this moment, I don't have any reason to think we'll have such tokens for another 6 months. Until there's a reason to think otherwise, that's the assumption from which I am speaking.

We also have 75 components and 8ish apps that exist and so will migrate multiple components and apps which also weren't created with the benefit of a design system. In https://github.com/opentable/buffet/issues/11, we're being encouraged to use this repo for the sake of alignment. But, even if we get some system tokens earlier, that won't be sufficient to migrate every component we might choose to migrate. We'll want in some cases to migrate "under the hood," from a purely technical perspective, so that we get the same visual result. Based on my experiences at OT so far, I think that restaurant design won't usually have the bandwidth to partner with us for those migrations, so we'll want to do so without having to put a whole design system or a redesign migration plan in place beforehand. That means we'll be creating unsystemitized tokens that we've ported from current work.

On a really fundamental level, I don't make choices based on my ideal vision of what I hope happens, I make them based on past experience and the current situation. My objective is to get any delaying factors or unnecessary process out of the way so that we have maximum speed and flexibility to do whatever moves the needle forward while best enabling us to use the result to advance our own design system dialog. If the situation changes, and it might, so will my current opinions, but that's what I have to go on right now.

**Closed** 2017-12-27 14:04 UTC
